/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import Entidad.Sistema;
import Entidad.Usuario;
import java.util.ArrayList;

/**
 *
 * @author cristian
 * @crramirezma
 */
public class FramePrincipal extends javax.swing.JFrame {
    
    private Registro registro =new Registro();
    private Ingreso ingreso=new Ingreso();
        

    public static Sistema sistema=new Sistema();
    
    
    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
        inicializacion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        registroBt = new javax.swing.JButton();
        ingresoBt = new javax.swing.JButton();
        panel_Principal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login de usuario");

        jToolBar1.setRollover(true);

        registroBt.setText("Registro");
        registroBt.setFocusable(false);
        registroBt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        registroBt.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        registroBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroBtActionPerformed(evt);
            }
        });
        jToolBar1.add(registroBt);

        ingresoBt.setText("Ingreso");
        ingresoBt.setFocusable(false);
        ingresoBt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ingresoBt.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ingresoBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoBtActionPerformed(evt);
            }
        });
        jToolBar1.add(ingresoBt);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel_Principal.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresoBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoBtActionPerformed
        // TODO add your handling code here:
        panel_Principal.setVisible(false);
        panel_Principal.removeAll();
        panel_Principal.add(ingreso);
        
        panel_Principal.setVisible(true);
    }//GEN-LAST:event_ingresoBtActionPerformed

    private void registroBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroBtActionPerformed
        // TODO add your handling code here:
        
        panel_Principal.setVisible(false);
        panel_Principal.removeAll();
        panel_Principal.add(registro);
        panel_Principal.setVisible(true);
    }//GEN-LAST:event_registroBtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }
    
    
    public void inicializacion(){
        ArrayList<Usuario> usuarios=new ArrayList<>();
        
        //generando usuarios con for
        Usuario usuario;
        for (int i = 0; i < 4; i++) {
            usuario=new Usuario();
            usuario.setNombre("Federico"+i);
            usuario.setPassword((12345*i)+"");
            usuarios.add(usuario);
        }
        
        sistema.setUsuarios(usuarios);
        
        for (Usuario usario:sistema.getUsuarios()) {
            System.out.println(usario.getNombre());
            System.out.println(usario.getPassword());
            System.out.println("--------------------");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ingresoBt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel panel_Principal;
    private javax.swing.JButton registroBt;
    // End of variables declaration//GEN-END:variables
}
